# Generated by Django 4.2.2 on 2023-06-19 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_groupcomments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupComments",
            new_name="PostComments",
        ),
    ]
