# Generated by Django 4.2.2 on 2023-06-15 21:07

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="about",
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(default="Unspecified", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Unspecified", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(default="Unspecified", max_length=500, null=True),
        ),
    ]
