# Generated by Django 4.2.2 on 2023-06-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_profile_bio_remove_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="profiles.profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="mentor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="mentor_expertise",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
