# Generated by Django 4.2.2 on 2023-06-16 22:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0005_profile_sent_requests_alter_friendrequest_from_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="profiles/",
            ),
        ),
    ]
