# Generated by Django 4.2.2 on 2023-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(default="Unspecified", max_length=100, null=True),
        ),
    ]
