# Generated by Django 4.2.2 on 2023-06-19 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mentors", "0002_remove_mentorrequest_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    djrichtextfield.models.RichTextField(
                        blank=True, default="No info", max_length=2500, null=True
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="mentorrequest",
            name="mentees",
        ),
        migrations.RemoveField(
            model_name="mentorrequest",
            name="mentor",
        ),
        migrations.DeleteModel(
            name="Mentor",
        ),
        migrations.DeleteModel(
            name="MentorRequest",
        ),
    ]
