# Generated by Django 4.2.2 on 2023-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_groupcomments_user_grouppost_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grouppost",
            options={"ordering": ["-posted_date"]},
        ),
        migrations.AddField(
            model_name="grouppost",
            name="posted_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
