# Generated by Django 4.2.2 on 2023-06-18 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_grouppost_options_grouppost_posted_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupcomments",
            old_name="group",
            new_name="post",
        ),
    ]
