# Generated by Django 4.2.2 on 2023-06-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_rename_group_groupcomments_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupcomments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comment",
                to="groups.grouppost",
            ),
        ),
    ]
